config/routes.rb
Newapp::Application.routes.draw do

  get "home/about"

  get "home/contact"

  root to: "home#index"

  get "about/index"

  get "contact/index"

  get "home/index"

  resources :products

  resources :sub_categories

  resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :sub_categories

  validates :name, :presence => true
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :brand, :description, :name, :price, :serial, :sub_category_id, :warranty_expire_at
  belongs_to :sub_category
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  attr_accessible :category_id, :name
  belongs_to :category
  has_many :products
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      
    end
  end

  # GET /categories/1
  
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      
    end
  end

  # GET /categories/new
  
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
      
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
 
  def create
    @category = Category.new(params[:category])

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        
      else
        format.html { render action: "new" }
        
      end
    end
  end

  # PUT /categories/1
 
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
       
      else
        format.html { render action: "edit" }
        
      end
    end
  end

  # DELETE /categories/1
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  # GET /products
  
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      
    end
  end

  # GET /products/1
  
  def show
    @product = Product.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      
    end
  end

  # GET /products/new
  
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
 
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        
      else
        format.html { render action: "new" }
       
      end
    end
  end

  # PUT /products/1
  
  def update
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        
      else
        format.html { render action: "edit" }
       
      end
    end
  end

  # DELETE /products/1
 
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      
    end
  end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  # GET /sub_categories
  
  def index
    @sub_categories = SubCategory.all

    respond_to do |format|
      format.html # index.html.erb
      
    end
  end

  # GET /sub_categories/1
  
  def show
    @sub_category = SubCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      
    end
  end

  # GET /sub_categories/new
  
  def new
    @sub_category = SubCategory.new

    respond_to do |format|
      format.html # new.html.erb
      
    end
  end

  # GET /sub_categories/1/edit
  def edit
    @sub_category = SubCategory.find(params[:id])
  end

  # POST /sub_categories
  
  def create
    @sub_category = SubCategory.new(params[:sub_category])

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully created.' }
        
      else
        format.html { render action: "new" }
        
      end
    end
  end

  # PUT /sub_categories/1
  
  def update
    @sub_category = SubCategory.find(params[:id])

    respond_to do |format|
      if @sub_category.update_attributes(params[:sub_category])
        format.html { redirect_to @sub_category, notice: 'Sub category was successfully updated.' }
       
      else
        format.html { render action: "edit" }
        
      end
    end
  end

  # DELETE /sub_categories/1
 
  def destroy
    @sub_category = SubCategory.find(params[:id])
    @sub_category.destroy

    respond_to do |format|
      format.html { redirect_to sub_categories_url }
      
    end
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/about/index.html.erb
<h1>About#index</h1>
<p>Find me in app/views/about/index.html.erb</p>

app/views/categories/_form.html.erb
<%= simple_form_for @category, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                categories_path, :class => 'btn' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/index.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= link_to category.id, category_path(category) %></td>
        <td><%= category.name %></td>
        <td><%=l category.created_at,:format => :short %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_category_path(category), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="form-actions">
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_category_path,
            :class => 'btn btn-primary' %>
</div>

app/views/categories/new.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/categories/show.html.erb
<%- model_class = Category -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @category.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              categories_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_category_path(@category), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              category_path(@category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/contact/index.html.erb
<h1>Contact</h1>
<p>8th Floor I&M Bank Tower, Kenyatta
Avenue - Muindi Mbingu Street
P.O. Box 8690-00200, City Square
Nairobi , Kenya</p>
<p>Mobile:+254 713046178</p>

app/views/home/about.html.erb
<h1>Inventory System</h1>
<p>This system enables a user to add an inventory of products in a database</p>

app/views/home/contact.html.erb
<h1>Our contacts</h1>
<p>8th Floor I&M Bank Tower, Kenyatta
Avenue - Muindi Mbingu Street
P.O. Box 8690-00200, City Square
Nairobi , Kenya</p>
<p>Mobile:+254 713046178</p>

app/views/home/index.html.erb
<h1>Welcome</h1>
<p>This is a demonstration of a inventory system</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inventory Apps</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 60px;
        color: #666;
      }
      a {
 color:#9F3B19;
}

a:hover {
color: #333;
} 
      /* Custom container */
      .container {
        margin: 0 auto;
        max-width: 1000px;
      }
      .container > hr {
        margin: 60px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 80px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 100px;
        line-height: 1;
      }
      .jumbotron .lead {
        font-size: 24px;
        line-height: 1.25;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }


      /* Customize the navbar links to be fill the entire space of the .navbar */
      .navbar .navbar-inner {
        padding: 0;
      }
      .navbar .nav {
        margin: 0;
        display: table;
        width: 100%;
      }
      .navbar .nav li {
        display: table-cell;
        width: 1%;
        float: none;
      }
      .navbar .nav li a {
        font-weight: bold;
        text-align: center;
        border-left: 1px solid rgba(255,255,255,.75);
        border-right: 1px solid rgba(0,0,0,.1);
      }
      .navbar .nav li:first-child a {
        border-left: 0;
        border-radius: 3px 0 0 3px;
      }
      .navbar .nav li:last-child a {
        border-right: 0;
        border-radius: 0 3px 3px 0;
      }
      aside h3 {
font-size: 18px;
line-height: 1.5em;
text-shadow: 0px 2px 3px #ddd;
}

#sidebar {
float: right;
overflow: hidden;
width: 280px;
margin-top: 20px;
}
aside ul {
list-style: square inside;
margin-bottom: 20px;
}
      footer {
margin-bottom: 20px;
clear:both;
}
h1,h2,h3,h4,h5,h6 {
font-weight: bold;
clear: both;
color: #333;
}
#footer-area {
border-top: 2px solid #9F3B19;
margin-top: -4px;
padding: 18px 0;
overflow: hidden;
}
.footer-segment {
float: left;
margin-right: 20px;
width: 210px;
}
    </style>
</head>
<body>
<div class="container">
 <header><!-- header -->
    <h2>Inventory App</h2>
     <%= image_tag('headerimg.jpg') %><!-- header image -->
  </header> 
<div class="masthead">

	<div class="navbar">
		<div class="navbar-inner">
			<div class="container">
				<ul class="nav">
					<li><%= link_to "Home", home_index_path %></li>
					<li><%= link_to "Product", products_path %></li>
					<li><%= link_to "Sub Category", sub_categories_path %></li>
					<li><%= link_to "Categories", categories_path %></li>
					<li><%= link_to "About", home_about_path %></li>
					<li><%= link_to "Contact", home_contact_path %></li>
				</ul>
			</div>
		</div>
	</div>
</div>
<% flash.each do |name, msg| %>
	<div class="alert alert-<%= name = :notice ? "success" : "error" %>">
		<a class="close" data-dismiss="alter">x</a>
		<%= msg %>
	</div>
<% end %>
<div class="row">
    <div class="span10"><%= yield %></div>
  </div>
<aside id="sidebar"><!-- sidebar -->
        <h3>Things To Do</h3>
          <ul>
            <li><a href="#">Play Games</a></li>
            <li><a href="#">Chat With Friends</a></li>
            <li><a href="#">Swap Stories</a></li>
            <li><a href="#">Sell Stuff</a></li>
            <li><a href="#">Buy Stuff</a></li>
            <li><a href="#">Trade Stuff</a></li>
          </ul>
          
        <h3>Our Sponsors</h3>
           <%= image_tag('ad125.jpg') %>  <%= image_tag('ad125.jpg') %><br />
           <%= image_tag('ad125.jpg') %>  <%= image_tag('ad125.jpg') %><br /><br />

        <h3>Connect With Us</h3>
          <ul>
            <li><a href="#">Twitter</a></li>
            <li><a href="#">Facebook</a></li>
          </ul>

    </aside><!-- end of sidebar -->
	
	<hr>
<footer>
    <section id="footer-area">

      <section id="footer-outer-block">
          <aside id="first" class="footer-segment">
              <h3>Blogroll</h3>
                <ul>
                  <li><a href="#">one linkylink</a></li>
                  <li><a href="#">two linkylinks</a></li>
                  <li><a href="#">three linkylinks</a></li>
                  <li><a href="#">four linkylinks</a></li>
                  <li><a href="#">five linkylinks</a></li>
                </ul>
          </aside><!-- end of #first footer segment -->

          <aside id="second" class="footer-segment">
              <h3>Awesome Stuff</h3>
                <ul>
                  <li><a href="#">one linkylink</a></li>
                  <li><a href="#">two linkylinks</a></li>
                  <li><a href="#">three linkylinks</a></li>
                  <li><a href="#">four linkylinks</a></li>
                  <li><a href="#">five linkylinks</a></li>
                </ul>
          </aside><!-- end of #second footer segment -->

          <aside id="third" class="footer-segment">
              <h3>Coolness</h3>
                <ul>
                  <li><a href="#">one linkylink</a></li>
                  <li><a href="#">two linkylinks</a></li>
                  <li><a href="#">three linkylinks</a></li>
                  <li><a href="#">four linkylinks</a></li>
                  <li><a href="#">five linkylinks</a></li>
                </ul>
          </aside><!-- end of #third footer segment -->
          
         

      </section><!-- end of #footer-outer-block -->

    </section><!-- end of #footer-area -->
  </footer>
</div>

</body>
</html>

app/views/products/_form.html.erb
<%= simple_form_for @product, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :sub_category_id %>
  <%= f.input :price %>
  <%= f.input :warranty_expire_at %>
  <%= f.input :brand %>
  <%= f.input :serial %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                products_path, :class => 'btn' %>
  </div>
<% end %>

app/views/products/edit.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/index.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:sub_category_id) %></th>
      <th><%= model_class.human_attribute_name(:price) %></th>
      <th><%= model_class.human_attribute_name(:warranty_expire_at) %></th>
      <th><%= model_class.human_attribute_name(:brand) %></th>
      <th><%= model_class.human_attribute_name(:serial) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= link_to product.id, product_path(product) %></td>
        <td><%= product.name %></td>
        <td><%= product.sub_category.name %></td>
        <td><%= product.price %></td>
        <td><%= product.warranty_expire_at %></td>
        <td><%= product.brand %></td>
        <td><%= product.serial %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_product_path(product), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      product_path(product),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="form-actions">
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_path,
            :class => 'btn btn-primary' %>
</div>

app/views/products/new.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/products/show.html.erb
<%- model_class = Product -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @product.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @product.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sub_category_id) %>:</strong></dt>
  <dd><%= @product.sub_category_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:price) %>:</strong></dt>
  <dd><%= @product.price %></dd>
  <dt><strong><%= model_class.human_attribute_name(:warranty_expire_at) %>:</strong></dt>
  <dd><%= @product.warranty_expire_at %></dd>
  <dt><strong><%= model_class.human_attribute_name(:brand) %>:</strong></dt>
  <dd><%= @product.brand %></dd>
  <dt><strong><%= model_class.human_attribute_name(:serial) %>:</strong></dt>
  <dd><%= @product.serial %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              products_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_path(@product), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_path(@product),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/sub_categories/_form.html.erb
<%= simple_form_for @sub_category, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :category_id %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                sub_categories_path, :class => 'btn' %>
  </div>
<% end %>

app/views/sub_categories/edit.html.erb
<%- model_class = SubCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sub_categories/index.html.erb
<%- model_class = SubCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:category_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @sub_categories.each do |sub_category| %>
      <tr>
        <td><%= link_to sub_category.id, sub_category_path(sub_category) %></td>
        <td><%= sub_category.name %></td>
        <td><%= sub_category.category.name %></td>
        <td><%=l sub_category.created_at,:format => :short %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_sub_category_path(sub_category), :class => 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="form-actions">
<%= link_to t('.new', :default => t("helpers.links.new")),
            new_sub_category_path,
            :class => 'btn btn-primary' %>
</div>

app/views/sub_categories/new.html.erb
<%- model_class = SubCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/sub_categories/show.html.erb
<%- model_class = SubCategory -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @sub_category.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:category_id) %>:</strong></dt>
  <dd><%= @sub_category.category_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              sub_categories_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_sub_category_path(@sub_category), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              sub_category_path(@sub_category),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>